// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqus_d4X40uKK40e_1Cc8uqTJpysVHJ5w',
    appId: '1:321067754411:web:4b2907fd750c58cadaa8ee',
    messagingSenderId: '321067754411',
    projectId: 'test-flutter-chat-app-72c78',
    authDomain: 'test-flutter-chat-app-72c78.firebaseapp.com',
    storageBucket: 'test-flutter-chat-app-72c78.appspot.com',
    measurementId: 'G-7Z21B4Z6Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ5dqCqA7_Bc6yLSEdf0ef07V9abOS660',
    appId: '1:321067754411:android:81c83d43d61b54badaa8ee',
    messagingSenderId: '321067754411',
    projectId: 'test-flutter-chat-app-72c78',
    storageBucket: 'test-flutter-chat-app-72c78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCasyoaE-BaOVIHCpEllbwDffUhuCL9HfU',
    appId: '1:321067754411:ios:6ef64a4f193b97e9daa8ee',
    messagingSenderId: '321067754411',
    projectId: 'test-flutter-chat-app-72c78',
    storageBucket: 'test-flutter-chat-app-72c78.appspot.com',
    iosBundleId: 'com.example.firstEverFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCasyoaE-BaOVIHCpEllbwDffUhuCL9HfU',
    appId: '1:321067754411:ios:6ef64a4f193b97e9daa8ee',
    messagingSenderId: '321067754411',
    projectId: 'test-flutter-chat-app-72c78',
    storageBucket: 'test-flutter-chat-app-72c78.appspot.com',
    iosBundleId: 'com.example.firstEverFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqus_d4X40uKK40e_1Cc8uqTJpysVHJ5w',
    appId: '1:321067754411:web:119e299de53ae51cdaa8ee',
    messagingSenderId: '321067754411',
    projectId: 'test-flutter-chat-app-72c78',
    authDomain: 'test-flutter-chat-app-72c78.firebaseapp.com',
    storageBucket: 'test-flutter-chat-app-72c78.appspot.com',
    measurementId: 'G-VJW06S1RLB',
  );

}